name: Windows (MinGW via MSYS2)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-fltk
          msystem: MINGW64

      - name: Configure (CMake)
        run: >
          cmake -S . -B build
          -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++"

      - name: Build
        run: cmake --build build --config Release -j 2

      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp build/BranchFormatter.exe dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BranchFormatter-windows
          path: dist
          if-no-files-found: error
